name: Auto Delete old workflow runs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'
    # Run monthly, at 00:00 on the 1st day of month.

jobs:
  Delete-Workflow-Archive:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Workflow Runs
        id: workflow
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 30
          keep_minimum_runs: 6
